# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: movie.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'movie.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmovie.proto\"\x1c\n\x0cMovieRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nMovieReply\x12\x0f\n\x07message\x18\x01 \x01(\t22\n\x05Movie\x12)\n\tListMovie\x12\r.MovieRequest\x1a\x0b.MovieReply\"\x00\x42,\n\x16\x63om.necisstudio.emovieB\nMovieProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movie_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.necisstudio.emovieB\nMovieProtoP\001\242\002\003HLW'
  _globals['_MOVIEREQUEST']._serialized_start=15
  _globals['_MOVIEREQUEST']._serialized_end=43
  _globals['_MOVIEREPLY']._serialized_start=45
  _globals['_MOVIEREPLY']._serialized_end=74
  _globals['_MOVIE']._serialized_start=76
  _globals['_MOVIE']._serialized_end=126
# @@protoc_insertion_point(module_scope)
